DATA SEGMENT
    MSG1 DB 10,13,"ENTER FIRST STRING : $"
    STRING1 DB 6,0,6 DUP('$')
    MSG2 DB 10,13,"ENTER SECOND STRING : $"
    STRING2 DB 6,0,6 DUP('$')  
    EQUAL_MSG DB 10,13,"THE STRINGS ARE EQUAL.$"
    UNEQUAL_MSG DB 10,13,"THE STRINGS ARE NOT EQUAL.$"
    PRINT MACRO ARG
        LEA DX,ARG
        MOV AH,09H
        INT 21H
    PRINT ENDM
    INPUT MACRO ARG
        LEA DX,ARG
        MOV AH,0AH
        INT 21H
    INPUT ENDM
DATA ENDS
CODE SEGMENT
    START:
    MOV AX,DATA
    MOV DS,AX 
    MOV ES,AX
    
    PRINT MSG1
    INPUT STRING1 
   ; PRINT STRING1+2
    PRINT MSG2
    INPUT STRING2 
    ;PRINT STRING1+2
    
    MOV SI,OFFSET STRING1+2
    MOV DI,OFFSET STRING2+2
    CLD
    
    REPE CMPSB
    ;CMP CX,0
    JNZ PRINT_NOTEQUAL
    ;JMP PRINT_EQUAL
    
    PRINT_EQUAL:
    PRINT EQUAL_MSG
    JMP END_PRG
    
    PRINT_NOTEQUAL:
    PRINT UNEQUAL_MSG
    
    END_PRG:
    MOV AH,4CH 
    INT 21H
    CODE ENDS
END START
      